### ISSUE TITLE
Fires go out instantly

### ISSUE THREAD

**Issue by Roet718** [Kenan2000/CDDA-Kenan-Modpack#1]
For some reason starting a fire in a brazier causes it to burn out in seconds without touching the fuel, regardless of amount of fuel in it.

**Comment by Theawesomeboophis** [comment]
Not a mod problem, this is a problem with vanilla.
https://github.com/CleverRaven/Cataclysm-DDA/pull/45431
https://github.com/CleverRaven/Cataclysm-DDA/issues/45318
See these for more info.

**Comment by Roet718** [comment]
thanks

**Comment by Theawesomeboophis** [comment]
No Problem.
