### ISSUE TITLE
BL9 Crash

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [Kenan2000/CDDA-Kenan-Modpack#109]
![Cataclysm Dark Days Ahead Screenshot 2021 07 04 - 18 42 01 47](https://user-images.githubusercontent.com/12477741/124391100-9d5bbd00-dcf7-11eb-8313-7f47af02564f.png)
After this game not running, crashed to main menu

**Comment by Kenan2000** [comment]
@ZSHADOWWOLF What version of Cataclysm you're playing? На новейшей экспериментальной версии формат поменяли, поэтому он такой, у вас неправильная версия, насколько я понял по ошибке

**Comment by ZSHADOWWOLF** [comment]
> 
> 
> @ZSHADOWWOLF What version of Cataclysm you're playing? На новейшей экспериментальной версии формат поменяли, поэтому он такой, у вас неправильная версия, насколько я понял по ошибке

Релиз 0.F

**Comment by Kenan2000** [comment]
> > @ZSHADOWWOLF What version of Cataclysm you're playing? На новейшей экспериментальной версии формат поменяли, поэтому он такой, у вас неправильная версия, насколько я понял по ошибке
> 
> Релиз 0.F

Используйте релиз версию в релизах модпака, там версия для новейшей стабильной версии

**Comment by Kenan2000** [comment]
@ZSHADOWWOLF Нажмите на Releases 3, чтобы все релизы были открыты при переходе на ссылку эту, так все релизы будут видны легко и понятно
