### ISSUE TITLE
Character creation bug(s)

### ISSUE THREAD

**Issue by Nephelos** [Kenan2000/CDDA-Kenan-Modpack#110]
Dont know where to report it at least for vamp stuff mod (vermillion mod also got that bug for another weapon i reported that on their github but im pretty sure that the author of that mod is inactive)

 DEBUG    : (json-error)
Json error: data/mods/vamp_stuff/Modification_Files/Items/Weapons/ranged_weapon.json:53:13: Invalid or misplaced field name "burst" in JSON data

    "recoil": 40,
    "durability": 7,
    "burst":
            ^
             3,
    "clip_size": 16,
    "reload": 80,

 FUNCTION : void JsonObject::report_unvisited() const
 FILE     : src/json.cpp
 LINE     : 122
 VERSION  : 1ddd145

Experimental version: 1ddd145 (tiles) / Build: 2021-07-04-1244

**Comment by Nephelos** [comment]
Also got a few more, im pretty sure they are related to blaze and modular turrets:

 DEBUG    : Wheel 'tread1' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 763
 VERSION  : 1ddd145

 DEBUG    : Wheel 'tread2' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 763
 VERSION  : 1ddd145

 DEBUG    : Wheel 'tread3' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 763
 VERSION  : 1ddd145

 DEBUG    : Wheel 'gloopletread' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 763
 VERSION  : 1ddd145

 DEBUG    : Wheel 'oozletread' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 763
 VERSION  : 1ddd145

 DEBUG    : Wheel 'graytread' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 763
 VERSION  : 1ddd145

 DEBUG    : Wheel 'graytread' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 763
 VERSION  : 1ddd145

 DEBUG    : Wheel 'gloople_wheel' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 763
 VERSION  : 1ddd145

 DEBUG    : Wheel 'gray_wheel' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 763
 VERSION  : 1ddd145

 DEBUG    : Wheel 'oozle_wheel' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 763
 VERSION  : 1ddd145

 DEBUG    : vehicle part mounted_acr uses undefined item acr

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 725
 VERSION  : 1ddd145

 DEBUG    : Missing item definition: acr

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1557
 VERSION  : 1ddd145

 DEBUG    : vehicle part mounted_acr has the TURRET flag, but is not made from a gun item

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 741
 VERSION  : 1ddd145

 DEBUG    : vehicle part mounted_h&k416a5 uses undefined item h&k416a5

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 725
 VERSION  : 1ddd145

 DEBUG    : Missing item definition: h&k416a5

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1557
 VERSION  : 1ddd145

 DEBUG    : vehicle part mounted_h&k416a5 has the TURRET flag, but is not made from a gun item

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 741
 VERSION  : 1ddd145

 DEBUG    : vehicle part mounted_m27iar uses undefined item m27iar

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 725
 VERSION  : 1ddd145

 DEBUG    : Missing item definition: m27iar

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1557
 VERSION  : 1ddd145

 DEBUG    : vehicle part mounted_m27iar has the TURRET flag, but is not made from a gun item

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 741
 VERSION  : 1ddd145

 DEBUG    : vehicle part mounted_m4a1 uses undefined item m4a1

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 725
 VERSION  : 1ddd145

 DEBUG    : Missing item definition: m4a1

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1557
 VERSION  : 1ddd145

 DEBUG    : vehicle part mounted_m4a1 has the TURRET flag, but is not made from a gun item

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 741
 VERSION  : 1ddd145

 DEBUG    : vehicle part mounted_scar_l uses undefined item scar_l

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 725
 VERSION  : 1ddd145

 DEBUG    : Missing item definition: scar_l

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1557
 VERSION  : 1ddd145

 DEBUG    : vehicle part mounted_scar_l has the TURRET flag, but is not made from a gun item

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 741
 VERSION  : 1ddd145

 DEBUG    : vehicle part wheel_caster_vo has unknown flag NO_JACK

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 683
 VERSION  : 1ddd145

Sorry about that mess Kenan :(

**Comment by stk2008** [comment]
The latest EXP seems to have killed a lot of mods.

![image](https://user-images.githubusercontent.com/8071418/124476108-5f63a500-dd9a-11eb-8092-16cf27085799.png)

**Comment by Theawesomeboophis** [comment]
Thanks, was gonna do this, got distracted. I'll help complete the list though with anything I find. I'm usually only available on weekends though.

**Comment by linonetwo** [comment]
can be closed, seems fixed

**Comment by Aoi-the-Hert** [comment]
idk i got this using both the latest commit and the latest release.
![image](https://user-images.githubusercontent.com/12159393/124540357-dfaef800-dde4-11eb-89b4-43ccff5a586d.png)

**Comment by Theawesomeboophis** [comment]
Looks like a missed burst, are all other mods working now at least?

**Comment by Theawesomeboophis** [comment]
Should be fixed in latest version of modpack.

**Comment by Nephelos** [comment]
Yeah these are fixed i think 😊 Im closing this issue now.
