### ISSUE TITLE
Duplicate construction id

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/CDDA-Kenan-Modpack#113]
DEBUG    : Error: Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/mods/Kenan-Modpack-Chinese/blazemod/recipes/blaze_construction_recipes.json:4:10: Duplicate construction id

  {
    "type": "construction",
    "id":
         ^
          "constr_blz_fridge_vehicle",
    "group": "convert_fridge_power_supply",
    "category": "FURN",

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/main_menu.cpp
 LINE     : 1149
 VERSION  : 1f0b625

**Comment by linonetwo** [comment]
I don't know how to solve this, I didn't find any duplicated id.

**Comment by Kenan2000** [comment]
If you're using both Blaze Industries along with Blazemod, it causes this problem technically

**Comment by linonetwo** [comment]
I thought blazeindustries will overwride blazemod when two recipes have same id...

What would you suggest? Disable built-in blazemod?

**Comment by linonetwo** [comment]
Okay

> Use instead of the new Blaze Industries mod in latest experimentals if continuing an with blazemod in it.

**Comment by linonetwo** [comment]
They used to work together...
