### ISSUE TITLE
Wheel 'wheel_monster' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/CDDA-Kenan-Modpack#117]
DEBUG    : Wheel 'wheel_monster' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/veh_type.cpp
 LINE     : 763
 VERSION  : 1f0b625

**Comment by Theawesomeboophis** [comment]
Which mod is it from?

**Comment by linonetwo** [comment]
I'm not familiar with this monster's design, so may need @Kenan2000 to fix this.

**Comment by Kenan2000** [comment]
This has been fixed in one of updates
