### ISSUE TITLE
Just a few ammo/mag errors

### ISSUE THREAD

**Issue by Nephelos** [Kenan2000/CDDA-Kenan-Modpack#118]
Experimental version: 6419e56 (tiles) / Build: 2021-07-06-1841

 DEBUG    : Tried to set ammo of 40x46mm_m433 without suitable magazine for m203_mod_smg

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of pebble without suitable magazine for tihar_vo

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of pebble without suitable magazine for vortexrifle

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of rebar_rail without suitable magazine for vortexcannon

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of bolt_wood without suitable magazine for vortexbolter

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of bb without suitable magazine for vortexaccelerator

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of charcoal without suitable magazine for diamondlance

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of arrow_wood without suitable magazine for invy_bow

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of 22_lr without suitable magazine for XBRbarrel

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of bolt_wood without suitable magazine for a22_bolter

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of arrow_wood without suitable magazine for airbower_succ

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of arrow_wood without suitable magazine for airbower

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of arrow_wood without suitable magazine for pneu_sniper

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of secro_flesh_boneneedle without suitable magazine for secro_power_armor_flesh_created_gun_bonerifle

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of charcoal without suitable magazine for diamondnova

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of pebble without suitable magazine for sur_pnu_lmg

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of ggp without suitable magazine for karlauncher

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of napalm without suitable magazine for boom_flamer

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of bloodypressure without suitable magazine for blood_sprayer

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of bloodypressure without suitable magazine for blood_stream_shooter

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of bloodypressure without suitable magazine for blood_stinger

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of bloodypressure without suitable magazine for bloodstinger_barrel

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of bloodypressure without suitable magazine for blood_slinger

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

 DEBUG    : Tried to set ammo of bloodshot_00 without suitable magazine for b11_striker

 FUNCTION : item& item::ammo_set(const itype_id&, int)
 FILE     : src/item.cpp
 LINE     : 617
 VERSION  : 6419e56

**Comment by Theawesomeboophis** [comment]
I think these were fixed in recent update, can you test to confirm this is the case?

**Comment by Nephelos** [comment]
This is fixed now thanks ❤ Im closing this one.
