### ISSUE TITLE
Bug during character creation (Magiclysm Revamp and Additions)

### ISSUE THREAD

**Issue by Nephelos** [Kenan2000/CDDA-Kenan-Modpack#120]
Experimental version: 8ce3dc5 (tiles)/Build: 2021-07-09-0030

 DEBUG    : Error: Json error: data/mods/MagicRevampAdditions/traits/attunements.json:137:23: Inline enchantment INLINE_ENCH_Force Mage_0 cannot be created as an enchantment already has this id.

    "prereqs": [ "MAGUS", "STORMSHAPER" ],
    "spells_learned": [ [ "force_blade", 5 ], [ "force_magical_armor", 5 ] ],
    "enchantments": [ {
                      ^
                        "condition": "ALWAYS", "values": [ { "value": "SPEED", "multiply": 0.2 } ] } ],
    "flags": [ "ATTUNEMENT" ]
  },

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 863
 VERSION  : 8ce3dc5

**Comment by Theawesomeboophis** [comment]
Fixed by Kenan recently ( I Think), can you test if the issue still occurs?

**Comment by Nephelos** [comment]
Nope it's still there, eventually will be fixed tho. Im just doing my part by reporting these errors 😊

**Comment by Nephelos** [comment]
I dont want to flood the issue page so here we go again, Bug during char creation (Jury Rigged Robots)

Experimental version: aa126fe (tiles)/Build: 2021-07-10-1214

 DEBUG    : Error: Json error: data/mods/Jury_Rigged_Robots/jrr_rigged_bots.json:177:23: tried to start object, but found '"', not '{'

    "death_drops": { "groups": [ [ "robots", 4 ] ] },
    "hp": 80,
    "death_function": "
                      ^
                       BROKEN",
    "special_attacks": [ [ "SHOCKSTORM", 17 ] ],
    "special_when_hit": [ "ZAPBACK", 10 ],


 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 863
 VERSION  : aa126fe



 DEBUG    : warnings for type boom_flamer:
problem with pocket: restricted to liquid item napalm but not watertight


 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1515
 VERSION  : aa126fe

**Comment by Theawesomeboophis** [comment]
I think your jury rigged robots is not updated, as meelock and kenan
changed all monsters to new mdeath system, unless they missed that entry.

**Comment by Nephelos** [comment]
Let me check again, with a fresh install.

**Comment by Theawesomeboophis** [comment]
Found error, gonna fix now

**Comment by Theawesomeboophis** [comment]
Fixed, just have to wait for merge.

**Comment by Theawesomeboophis** [comment]
BTW are you using Magiclysm?

**Comment by Theawesomeboophis** [comment]
Can you test fix I submitted and see if magic revamp still throws an error?

**Comment by Theawesomeboophis** [comment]
Fixed by Kenan.

**Comment by Nephelos** [comment]
Ok its working now 😊 Thanks guys❤, tho i still got a skippable bug:

 DEBUG    : warnings for type boom_flamer:
problem with pocket: restricted to liquid item napalm but not watertight


 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1515
 VERSION  : aa126fe

**Comment by Theawesomeboophis** [comment]
> Ok its working now  Thanks guys, tho i still got a skippable bug:
> 
> DEBUG : warnings for type boom_flamer:
> problem with pocket: restricted to liquid item napalm but not watertight
> 
> FUNCTION : void Item_factory::check_definitions() const
> FILE : src/item_factory.cpp
> LINE : 1515
> VERSION : aa126fe

Which Mod is the error from?

**Comment by Nephelos** [comment]
Im pretty sure its the base game and not any mod. Its occurring during char creation/save loading at the finalizing part Materials section (?).
