### ISSUE TITLE
Changes to Monster death function on experiemental basically broke everything (again)

### ISSUE THREAD

**Issue by TheEventHorizon** [Kenan2000/CDDA-Kenan-Modpack#123]
A recent [commit](https://github.com/CleverRaven/Cataclysm-DDA/pull/49439) on experimental changed how the death function spell works. Now every mod with monsters needs to be updated. Fun times.
[debug.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/6794172/debug.log)

**Comment by Theawesomeboophis** [comment]
I'll attempt fixing all mods tomorrow, any idea what new death function replaced "NORMAL"? I can't seem to find the replacement in the PR.

**Comment by TheEventHorizon** [comment]
No rush, I was planning on doing the same thing 😝 But in regards to what to replace "NORMAL" with, it seems that based on the changes made in that PR if the death functions was listed as normal, you just omit a death function call entirely when updating. I say this because when I looked through the files that were changed in the PR the monsters who only had normal as a death function don't have that line at all after the change and the monsters that did have unique death effects were updated to the new array format.

**Comment by Theawesomeboophis** [comment]
Okay, thanks, I'll begin working on this in the morning.

**Comment by meelock** [comment]
Mostly done, will be worth adding comments where we removed multiple effects.

**Comment by Theawesomeboophis** [comment]
Nevermind, Meelock and Kenan already fixed everything.
