### ISSUE TITLE
Secronom lore expansion error

### ISSUE THREAD

**Issue by EPIC2X** [Kenan2000/CDDA-Kenan-Modpack#130]
Im on experimental build: 2021-07-09-2342 , Win64
(This is my first time posting an issue of anything on github, so apologizes if i didn't do it correctly)
(Edit: I completely forgot to mention that this was during the initial load up before character creation) 
![image](https://user-images.githubusercontent.com/87242564/125172450-70882980-e17f-11eb-8714-5323b04e1e6c.png)

**Comment by EPIC2X** [comment]
Small update, just tried it on experimental build 2021-07-10-1214 and got the same error

**Comment by Kenan2000** [comment]
@EPIC2X What? This makes no sense ```{
    "id": "secro_id_fvvault_open",
    "type": "SPELL",
    "name": { "str": "Identify" },
    "description": "Item is swapped to the door's card reader. If successful, opens specific doors.",
    "flags": [ "SILENT", "NO_PROJECTILE" ],
    "message": "",
    "valid_targets": [ "ground" ],
    "effect": "ter_transform",
    "shape": "blast",
    "effect_str": "secro_fvvault",
    "min_range": 1,
    "max_range": 1,
    "base_casting_time": -1
  },```, it is included, why would it throw an error if shape entry is included here?

**Comment by EPIC2X** [comment]
@Kenan2000  im not sure, but you can see the screenshot of what its yelling at me, i thought it was odd as well

**Comment by Kenan2000** [comment]
Try reinstalling mods, this makes no sense, if this file in your cdda/data/mods/secronom_lore_expansion does not contain "shape", it's a problem with installation, if it contains it yet still throws an error, we'll hopefully look into this

**Comment by EPIC2X** [comment]
iv reinstalled the pack like 3 times, so im going to try downloading the experimental version directly instead of using the launcher, and i'll report back if that helps

**Comment by EPIC2X** [comment]
I think im going to scream...
(I installed a fresh new CDDA, and im not getting the Secronom error now, but im getting an error from blazemod)
![image](https://user-images.githubusercontent.com/87242564/125176381-9110ad80-e198-11eb-9261-205ad965d6e1.png)

**Comment by Theawesomeboophis** [comment]
> I think im going to scream...
> (I installed a fresh new CDDA, and im not getting the Secronom error now, but im getting an error from blazemod)
> ![image](https://user-images.githubusercontent.com/87242564/125176381-9110ad80-e198-11eb-9261-205ad965d6e1.png)

Completely delete all mod folders from file location and reinstall all mod folders from here. If that doesn't work it's probably a larger issue, but I suspect these are ghost errors.

**Comment by Theawesomeboophis** [comment]
> I think im going to scream...
> (I installed a fresh new CDDA, and im not getting the Secronom error now, but im getting an error from blazemod)
> ![image](https://user-images.githubusercontent.com/87242564/125176381-9110ad80-e198-11eb-9261-205ad965d6e1.png)

I have no idea what's going on here, from the first image, the effect_str should be id as it is in the files, these errors look to be nonexistant, and if a full reinstall did not help, I am not sure what will.

**Comment by Theawesomeboophis** [comment]
Can you send your modlist.

**Comment by EPIC2X** [comment]
[mods.txt](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/6795972/mods.txt)
That should be correct (never had to do this before), Im pretty much using almost every mod in the modpack

**Comment by Theawesomeboophis** [comment]
I see a problem immediately, you're using BlazeIndustries and Blazemod, they are no longer compatible with each other, try removing BlazeIndustries and see if the error persists.

**Comment by EPIC2X** [comment]
Now im getting a crash when generating a character, the crash happens when its finalizing crafting recipes (it also doesn't give a message, it just CTD)

**Comment by EPIC2X** [comment]
Ok, so now i know the game works from a fresh install without the modpack installed, now im just going to go through all the mods and try to figure out whats the problem.

**Comment by EPIC2X** [comment]
Uhhh, so i have no idea what i did, but apparently it works now. I reinstalled CDDA on a different drive, enabled all the mods in small groupings (to speed it up) until i had all the mods i wanted enabled and then it crashed, so i started turning them off in smaller groups then i turned them on and it still kept crashing until all the mods were gone, i then enabled all the mods again in very small groups (like 3 at a time small) and now all the mods i wanted (which was most of them) are on and its now working. I am peak confusion right now and guess im going to close this issue. Thanks for the attempt of help, im glad that atleast i wasnt the only one who got confused from this.

**Comment by Theawesomeboophis** [comment]
This predicament was indeed odd and confusing, at least it's fixed now,
hopefully it continues working, keep the days ahead dark and enjoy death
now that everything seems fixed.
