### ISSUE TITLE
Naming error in DeoxyMod

### ISSUE THREAD

**Issue by karnadit** [Kenan2000/CDDA-Kenan-Modpack#131]
In Deoxy_vehicle_parts.json Line 160 should read  "name": { "str": "upgraded solar panel" },
This error changes all installed "upgraded solar panel" to read "quantum solar panel" instead.

Here is what it currently says.

{
    "id": "solar_panel_v2",
    "copy-from": "solar_panel_v2",
    "type": "vehicle_part",
    "name": { "str": "quantum solar panel" },
    "extend": { "flags": [ "FOLDABLE" ] },
    "folded_volume": "4500 ml"
    
    Sorry if this is the wrong area/way to submit this. This error has been in for a long time I had just been manually fixing it in my local files

**Comment by Theawesomeboophis** [comment]
This is correct, they are 2 separate items from what I gather, I will work on making them not so similar by changing quantum solar panel's volume to be different from upgraded solar panel.

**Comment by Theawesomeboophis** [comment]
It was a duplicate ID, now they should not replace each other.
