### ISSUE TITLE
"default_oter"  json error

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/CDDA-Kenan-Modpack#134]
origin
![Screenshot_20210716_100358_com cleverraven cataclysmdda experimental](https://user-images.githubusercontent.com/22638873/125881297-2c1a602c-19be-4cec-b618-268594b8fcb5.jpg)

edit by myself
![Screenshot_20210716_101030_com cleverraven cataclysmdda experimental](https://user-images.githubusercontent.com/22638873/125881319-e7a92df3-8e82-40ba-856e-7b50a4ca39f2.jpg)

official example
![Screenshot_20210716_100945](https://user-images.githubusercontent.com/22638873/125881350-fa35dcfb-2bd8-4c62-a6b5-329b1ab4e9d4.jpg)

**Comment by waveyl** [comment]
version: game: 2021-07-14-2206
modpack: latest master

**Comment by waveyl** [comment]
@Night-Pryanik

**Comment by Kenan2000** [comment]
@waveyl Working on fixing this, please, don't ping developers here, they are not particularly fond of Modpacks, this work is of our community, of me, only we are involved in making these mods work as well

**Comment by waveyl** [comment]
> @waveyl Working on fixing this, please, don't ping developers here, they are not particularly fond of Modpacks, this work is of our community, of me, only we are involved in making these mods work as well

I'm sorry

**Comment by Kenan2000** [comment]
This has been fixed in latest update, @waveyl, check it when you have time as well :-)
