### ISSUE TITLE
Can you please post a picture of the load order you use? I am having a lot of conflicts running the mods and the game just crashes (running latest experimental updated from the launcher) Thanks!)

### ISSUE THREAD

**Issue by KrakenHunter** [Kenan2000/CDDA-Kenan-Modpack#135]

**Comment by Kenan2000** [comment]
@KrakenHunter We are, I am working on fixing these issues, we are, I am aware of them, you are not supposed to enable all mods together, enable only what you like, there is no set load order, you can enable whatever you want
