### ISSUE TITLE
Misc Errors 2

### ISSUE THREAD

**Issue by Theawesomeboophis** [Kenan2000/CDDA-Kenan-Modpack#139]
DEBUG    : Wheel 'secro_flesh_wheel_leg' lacks either 'UNSTABLE_WHEEL' or 'STABLE' flag.

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 763
 VERSION  : d1d5c52
 DEBUG    : vehicle part mounted_acr uses undefined item acr

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 725
 VERSION  : d1d5c52
 DEBUG    : Missing item definition: acr

 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1638
 VERSION  : d1d5c52
 DEBUG    : vehicle part mounted_acr has the TURRET flag, but is not made from a gun item

 FUNCTION : static void vpart_info::check()
 FILE     : src/veh_type.cpp
 LINE     : 741
 VERSION  : d1d5c52
Misc Errors that the game reported on latest experimental, seem to originate from secronom and possibly blazemod.

**Comment by Kenan2000** [comment]
@Theawesomeboophis Hmm, cannot replicate this on latest experimental version, try to reinstall your CDDA folder with all mods entirely, this should work maybe

**Comment by Theawesomeboophis** [comment]
Okay, I'll try that.

**Comment by Theawesomeboophis** [comment]
I tried reinstalling the suspect mods and the errors still appear, not sure what's happening.

**Comment by Theawesomeboophis** [comment]
I have attempted reinstalling the mods, errors still appear, not sure what's happening, they're not game-breaking, so it should be fine. Thanks.

**Comment by Theawesomeboophis** [comment]
I can't find any secronom vehicle part with this id in lore expanded or the main mod, it's most likely ghost errors.

**Comment by Kenan2000** [comment]
In one of Secronom updates, Axema removed vehicle parts from Secronom, renaming vehicle_parts json file to vehicle_parts txt, try to check if this file still exists in your mod folder, if these errors still appear, try to reinstall your CDDA game entirely to make sure that old mod folders are deleted so you can do a clean update of some sorts as well

**Comment by Theawesomeboophis** [comment]
I'll check for that file, thanks.

**Comment by Theawesomeboophis** [comment]
The secronom errors disappeared after deleting the obsolete file, the acr errors still occur though, any idea what's causing them?

**Comment by Kenan2000** [comment]
Honestly, no idea where this error comes from, it could be older version of blazemod or secronom, but not sure honestly

**Comment by Kenan2000** [comment]
Honestly, not sure where these errors come from, it could be older version of blazemod or older version of secronom, try checking them as well

**Comment by Theawesomeboophis** [comment]
I checked blazemod, blazeindustries and vorpal weapons to no avail, I see no mention of a mounted acr anywhere.

**Comment by Theawesomeboophis** [comment]
Issue fixed itself.
