### ISSUE TITLE
CTD on "Cut" objects action when using small mod selection

### ISSUE THREAD

**Issue by Beetlecat** [Kenan2000/CDDA-Kenan-Modpack#141]
Hello  -- Looking for some assistance on a consistent crash, and since I'm using the full modpack (with no other additions) I wanted to start here.

- Game is current experimental (and tested back over the last 5-6 updates) ver _2021-08-16-1305_
- Most recent github download of Modpack
- Most recent github download of SDG's tileset

Using a minimal set of mods, I'm experiencing a CTD when attempting to "Cut up" an item on the ground or in inventory from the Butcher menu, or even a knife action menu.

-   "dda"
-   "no_npc_food"
-   "jury_rigged_robots"
-   "aftershock"
-   "modular_turrets_no_blacklist"
-   "Salvaged_Robots"

I've initially solved it by removing _Jury Rigged Robots_ from my main game, but that mod works fine if used alone with DDA.
If I also introduce _Salvaged Robots_ (& its two dependencies) I get the crash.

Am I doubling up on mods/content? Are either of these already incorporated into Aftershock?

Thanks for your help!

**Comment by Kenan2000** [comment]
@Beetlecat Could you provide pictures or elaborate explanation of action that you’re doing in-game so that it would be easier to reproduce? Does this issue persist when cutting up all items or only particular items? 

Amount of mods that you’re using is really small, not big enough to cause any inconsistency problems, if you provide more details, it would be possible for me to test doing these actions in-game with these mods on to see what exactly causes this issue here as well

**Comment by Beetlecat** [comment]
Sure - I could grab a screenshot in a bit, but the simplest explanation is to attempt to **Cut up** anything that allows that action in the **B**utcher menu, such as sheets, long string, or sticks after pulling down curtains. Selecting **Cut up** item in a knife's action menu would also result in the CTD for me.

Like this pile of stuff here:
![scene](https://user-images.githubusercontent.com/2371787/129650493-77f5539f-904d-433c-87b5-eaa4c5f847e2.png)

And [B] menu when standing over them:
![action](https://user-images.githubusercontent.com/2371787/129650481-cae718dc-1c5d-48ab-89cd-18fbada11979.png)

Selecting either of those results in an instant CTD.

**Comment by Kenan2000** [comment]
@Beetlecat Hmm, on latest experimental CDDA version I've spawned a knife, spawned sheets, sticks, clothes, I've tested fboth disassembling, cutting too, it does not crash nor causes CTD, but here's a thing, I've changed dependencies of Salvaged Robots, Modular Turrets to not rely on Aftershock, so with Jury Rigged Robots, Salvaged Robots, Modular Turrets, this issue cannot be replicated, could you please try to do exactly same thing, if it works, do it again but with Aftershock, Jury Rigged Robots, Salvaged Robots, Modular Turrets enabled together if this issue persists as well?

**Comment by Beetlecat** [comment]
@Kenan2000  Hah! Oh, wow.

I love it when relatively simple experiments don't match results.  I *did* also have "no_npc_food" loaded in that world, but that should hardly have conflicted. Did you say you *didn't* have aftershock installed in your test? I'll try a world w/o that as well.

To start, I'll simply update to the latest experimental, since one or two updates may have dropped in the meantime.

**Comment by Beetlecat** [comment]
Okay, paring down the mods a bit more (to only DDA + test mods) --

The current experimental (2021-08-17-1736) made no change.
- Removed Aftershock from the initial list and I can Cut up objects fine with no CTD.
- Just Aftershock by itself: no CTD
- Just Aftershock + Jury Rigged Robots: CTD when cutting objects.

**Comment by Theawesomeboophis** [comment]
It seems to be a compatibility issue between JRR and Aftershock, not sure what's causing it to occur, the fact that it only occurs when cutting items is also very peculiar.

**Comment by Malkeus** [comment]
I am getting a very similar, probably identical, bug involving 'Magiclysm Revamp and Additions'. It is inconsistent though. The world with the cut issue includes 99% of kenans pack for dda plus a few I got from forum. After narrowing things down I ended up with a copy that has only MRA removed from the list and suddenly cut stops CTDing. But removing MRA from load of original world didn't fix the issue there. The functional copy includes Aftershock with JRR, salvaged bots, modular turrets from kenans pack. I plan to make a world per the op to see if I can duplicate the issue and then update n try again.

**Comment by Theawesomeboophis** [comment]
I think Kenan fixed this in a recent update ( I know he fixed JRR at least). Is the error still occurring?

**Comment by Beetlecat** [comment]
Thanks for the reminder -- as of the most recent suite of updates of Main CDDA Experimental+Modpack, re-adding JRR back does not result in CTD with cutting. Hooray!  Consider this one tied up, even if no clear cause/solution was discovered. ;)

**Comment by Beetlecat** [comment]
> I am getting a very similar, probably identical, bug involving 'Magiclysm Revamp and Additions'. It is inconsistent though. The world with the cut issue includes 99% of kenans pack for dda plus a few I got from forum. After narrowing things down I ended up with a copy that has only MRA removed from the list and suddenly cut stops CTDing. But removing MRA from load of original world didn't fix the issue there. The functional copy includes Aftershock with JRR, salvaged bots, modular turrets from kenans pack. I plan to make a world per the op to see if I can duplicate the issue and then update n try again.
> Edit: I can't do it with the op setup, seems to only trigger for me when Magiclysm n MRA are involved. I hope updating fixes it, I like those unrestricted spells.
> Edit: Updating wasn't a magic bullet. 🤣
> 
> Edit: pks rebalance and Aftershock are causing the same crash.

I didn't get the same results with that combo of mods, either. Is it working now?
