### ISSUE TITLE
Catacylsm++ Radiogenic Goggles Lit Up Permanent

### ISSUE THREAD

**Issue by VaneFox** [Kenan2000/CDDA-Kenan-Modpack#151]
The goggles will cause you to permanently have the lit up effect, just by having them in your inventory. Also light up the space around them when dropped. Can't turn off and requires no charge.

![cataclysm-tiles_2021-08-30_00-32-36](https://user-images.githubusercontent.com/67852696/131255348-836484e1-7186-4a39-8eb4-13db66f230f8.png)
![cataclysm-tiles_2021-08-30_00-33-02](https://user-images.githubusercontent.com/67852696/131255353-463fc143-00a9-4f98-a1b1-cccef6e589b0.png)
![cataclysm-tiles_2021-08-30_00-33-15](https://user-images.githubusercontent.com/67852696/131255355-701f7f04-76cc-4d5a-8c8c-634ef74b64cb.png)

**Comment by Kenan2000** [comment]
@VaneFox This technically seems to be an intended behavior, this link https://github.com/Noctifer-de-Mortem/nocts_cata_mod, here, is a link to official mod's GitHub repository where authors are actually working on adding content for it, feel free to post this issue on it's official page, but this seems to be an intended behavior as well

**Comment by VaneFox** [comment]
Thanks for the hub link! I did try looking for it, appears it's under a different name, thank you!
