### ISSUE TITLE
Invalid Ammo Type

### ISSUE THREAD

**Issue by Theawesomeboophis** [Kenan2000/CDDA-Kenan-Modpack#157]
DEBUG : Tried to get invalid ammunition: fusion

FUNCTION : const T& string_id::obj() const [with T = ammunition_type]
FILE : src/ammo.cpp
LINE : 53
VERSION : 0138041
I get this error while loading.
Edit: I have checked and it is not from Bootleg Walkers.

**Comment by linonetwo** [comment]
omg, there are tons of errors in latest experimental release

**Comment by Beetlecat** [comment]
> omg, there are tons of errors in latest experimental release

Yeah, I updated like an idiot, and forgot which version I was on previous. :D
