### ISSUE TITLE
Dorf Life Non-Function

### ISSUE THREAD

**Issue by VaneFox** [Kenan2000/CDDA-Kenan-Modpack#158]
Dorf Life seems to consistently cause a crash to menu at "mapgen weights" any time I attempt to use it on new world gens. Either doesn't function alone or with any number of other mods that affect map gen.

**Comment by linonetwo** [comment]
Yes, so sad, can you make a PR to fix this?

**Comment by linonetwo** [comment]
There are too many things to fix, we must share our load.

**Comment by Kenan2000** [comment]
I've fixed many issues including these ones that you mention in this update https://github.com/Kenan2000/CDDA-Kenan-Modpack/commit/5abe944030d8c7e002de0aaa1cbf11920ef44ab8, be patient a bit :-)
