### ISSUE TITLE
item group "NC_JUNK_SHOPKEEP_misc" already defined with type "collection"

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/CDDA-Kenan-Modpack#161]
DEBUG    : Error: item group "NC_JUNK_SHOPKEEP_misc" already defined with type "collection"

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/main_menu.cpp
 LINE     : 857
 VERSION  : adf846b

**Comment by Theawesomeboophis** [comment]
This error seems to come from Arcana.

**Comment by linonetwo** [comment]
Moved there
