### ISSUE TITLE
invalid monster flag: "CATFOOD"

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/CDDA-Kenan-Modpack#166]
DEBUG    : Error: Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/mods/Kenan-Modpack-Chinese/Fallout_CDDA/FEV Experimentation/antifungal_ants.json:60:7: invalid monster flag: "CATFOOD"

      "CHITIN",
      "CLIMBS",
      "
      ^
       CATFOOD",
      "DOGFOOD",
      "BIRDFOOD",

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : /home/runner/work/Cataclysm-DDA/Cataclysm-DDA/android/app/jni/src/../../../../src/main_menu.cpp
 LINE     : 857
 VERSION  : e341785

**Comment by Kenan2000** [comment]
Try to check if it's fixed with latest update hopefully as well

**Comment by linonetwo** [comment]
Thank you, this fixes it.
