### ISSUE TITLE
[Valkyria_mod]Can't reload the Gallian-1

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/CDDA-Kenan-Modpack#179]
![image](https://user-images.githubusercontent.com/22638873/135560226-b4bfc9db-df5a-4010-9218-8f39eb7dbae1.png)

**Comment by Kenan2000** [comment]
@waveyl Latest update fixes this hopefully as well

**Comment by waveyl** [comment]
@Kenan2000 Still appeared
