### ISSUE TITLE
Expanded Archery circular dependency bug

### ISSUE THREAD

**Issue by Nephelos** [Kenan2000/CDDA-Kenan-Modpack#185]
I got this bug during char creation :

 DEBUG    : (json-error)
Json error: data/mods/Expanded_Archery_Temp_Lite_Version/Attachments.json:2:3: JSON contains circular dependency, this object is discarded

[
  {
  ^

    "id": "tuned_mechanism",
    "type": "GUNMOD",

 FUNCTION : void DynamicDataLoader::load_deferred(DynamicDataLoader::deferred_json&)
 FILE     : src/init.cpp
 LINE     : 182
 VERSION  : 10f9006

**Comment by Kenan2000** [comment]
@Nephelos It's fixed in latest updates hopefully as well
