### ISSUE TITLE
Invalid body parts

### ISSUE THREAD

**Issue by Maryionet** [Kenan2000/CDDA-Kenan-Modpack#186]
![Screenshot_20211008-185843_Cataclysm DDA (experimental)](https://user-images.githubusercontent.com/68288642/136547713-bef0f7b4-2b4f-4736-8a50-9b5c1bf52239.jpg)
[debug.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/7311075/debug.log)
For some reason when i'm scrolling down on item list on letter V it shows this error and it closes the game

**Comment by Kenan2000** [comment]
@Maryionet It's fixed in latest updates hopefully as well
