### ISSUE TITLE
[Extra Professions & Gears]cannot specify clip_size or magazine without ammo type

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/CDDA-Kenan-Modpack#189]
DEBUG    : warnings for type cddaxp_r135ppgm:
cannot specify clip_size or magazine without ammo type

 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1613
 VERSION  : d90c615

**Comment by Kenan2000** [comment]
@waveyl Please, convert similar issues into a single issue via comments, in this case move this issue to errors about circular dependency made by linonetwo, it's a bit confusing when a lot of similar issues are published as different ones, hopefully you don't mind this as well
