### ISSUE TITLE
Some bugs caused by removed items

### ISSUE THREAD

**Issue by waveyl** [Kenan2000/CDDA-Kenan-Modpack#190]
DEBUG    : profession cddaxp_rioteer: item flamethrower_crude does not exist

 DEBUG    : warnings for type ria_30_strikeforce:
problem with pocket: item_id USAS10mag used in restriction invalid

**Comment by Kenan2000** [comment]
@waveyl Please, convert similar issues into a single issue via comments, in this case move this issue to errors about circular dependency made by linonetwo, it's a bit confusing when a lot of similar issues are published as different ones, hopefully you don't mind this as well
