### ISSUE TITLE
cddaxp_r135ppgm: cannot specify clip_size or magazine without ammo type

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/CDDA-Kenan-Modpack#195]
DEBUG    : warnings for type cddaxp_r135ppgm:
cannot specify clip_size or magazine without ammo type

 FUNCTION : void Item_factory::check_definitions() const
 FILE     : src/item_factory.cpp
 LINE     : 1613
 VERSION  : 8256058

**Comment by Kenan2000** [comment]
@linonetwo Hopefully fixed in latest version as well
