### ISSUE TITLE
Segmentation fault when reloading 25mm chaingun

### ISSUE THREAD

**Issue by hitmancho** [Kenan2000/CDDA-Kenan-Modpack#2]
I am getting a segfault crash every time I try to reload an IFV's chaincannon with an ammo belt in my current game (experimental #11181). I am attaching the crash log here. I apologise if this is not caused by one of the installed mods, but I think Infantry Fighting Vehicles and their 25mm cannons are not part of the stock mods or BlazeIndustries.

Edit: This is also happening when reloading a 152mm HEAT shell into the main cannon. Cannot say a 100% it happens to all mounted turrets. I am talking about a wrecked Bradley IFV in the game with intact turrets that I am firing and reloading manually.
[crash.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/5579623/crash.log)

Mods Active:
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "aftershock",
  "Arcana",
  "blazeindustries",
  "crt_expansion",
  "magiclysm",
  "rice",
  "adv_gear",
  "advtech",
  "ArmUpSurvEx",
  "arsenal_breach",
  "Tolerate_This",
  "CBM_Arms",
  "SD_Magcrafting",
  "craftgp",
  "dried_fruits",
  "ExArch",
  "growable-pots",
  "Gourmand'sGraces",
  "homestead",
  "Medieval_Mod_Reborn",
  "demon_spider_a",
  "More tea leaf",
  "modern_weapon",
  "MST_Extra",
  "apex",
  "CerealMod",
  "PK_REBALANCE",
  "Cata++",
  "noctpk",
  "modular_turrets_no_blacklist",
  "Salvaged_Robots",
  "hydroponics",
  "Mining_Mod",
  "more_survivor_stuff",
  "more_npc",
  "zets_hair_extensions_undead",
  "more_locations",
  "zets_hair_ext_more_locations",
  "zets_hair_ext_pk_rebalance",
  "No_Rail_Stations",
  "blazemod",
  "Heavy miners",
  "Tankmod_Revived",
  "AftershockUDP",
  "MagiclysmUDP",
  "BlazeIndustriesUDP",
  "more_locationsUDP",
  "UDP_XOTTO_INDICATORS",
  "Arts' Guns",
  "jury_rigged_robots",
  "Merchant",
  "fuji_mpp",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills"

**Comment by Kenan2000** [comment]
@hitmancho first of all - you **MUST NOT USE** both Blaze Industries and Blazemod - remove Blaze Industries and use Blazemod only - Blazemod is the updated and more improved version of Blaze Industries - this could be potentially causing tons of problems

Moreover, I believe that IFV Bradley vehicle is from Tankmod_revived, tell me if the issue still persists with Blaze Industries mod removed (remove it from your `cdda/save/mods.json` file as well), together we'll be able to fix this issue, what is the name of the gun that you're using?Is it this:

```M242 Bushmaster autocannon - "description": "A chain-driven autocannon chambered in 25x137mm, designed for the Bradley IFV and other ground vehicles, with some naval use as well.  Electric-driven, it needs to be mounted on a vehicle to fire.",``` ?

**Comment by Kenan2000** [comment]
Moreover, you don't need to use UDP mods at this point - all of the mods in my modpack have tiles incorporated into them - all you have to do is get the latest version of SDG's tileset and it's all gonna work smoothly and nicely

**Comment by chaosvolt** [comment]
I just tested that build in vanilla and tried to reload the TOW-equipped humvee:
![image](https://user-images.githubusercontent.com/11582235/99911526-af35a600-2cba-11eb-8f20-7ea16b7ee5b4.png)

Looks like possibly https://github.com/CleverRaven/Cataclysm-DDA/issues/41268 was never actually fixed.

**Comment by hitmancho** [comment]
Thanks for the heads-up I removed BlazeIndustries from my save as well as from mods without any extra issues. As for the turrets - this should indeed from Tankmod, both the Bushmaster, as well as the 152mm ATGM. I get segmentation faults reloading the latter as well. Here is a log after I crashed trying to put a 152mm shell in (not a belt).
[crash.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/5579984/crash.log)

@chaosvolt I am guessing it should be the same, since this is my error message too. Since my run is heavily modded I doubt I should reports this to the main game repo. Any advice or solutions I could wait for?

**Comment by chaosvolt** [comment]
Yeah, the 25mm chaingun is from Tankmod: Revived. It also had a two-shot ATGM launcher. Vanilla has one-round ATGM tubs as well, and uses them on one humvee variant.

I'd suggest testing other vanilla vehicles, seeing what else segfaults, then opening an issue for it.

**Comment by Roet718** [comment]
Same thing happens with the mounted M249

**Comment by chaosvolt** [comment]
Looks like a PR was merged yesterday that claims to fix it, https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-jenkins-b11182 might be a release to test out once it's built enough. Right now it's still building.

**Comment by Kenan2000** [comment]
Considering that this is a vanilla issue, I'm closing this
