### ISSUE TITLE
Some additional missing materials

### ISSUE THREAD

**Issue by Nephelos** [Kenan2000/CDDA-Kenan-Modpack#225]
DEBUG    : Error: Json error: data/mods/MagicRevampAdditions/Spells_Override/attunements/Force_Mage.json:60:3: missing mandatory member "material"

      }
    ]
  }
  ^
   ,
  {
    "id": "force_magical_armor",

 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1145
 VERSION  : 0ad2fdd

Build: 2021-10-29-0833

And please do not close this issue once this is resolved, im going to collect here the rest of the missing ones from mods im using. ❤

**Comment by Nephelos** [comment]
DEBUG    : Error: Json error: data/mods/MagicRevampAdditions/Spells_Override/attunements/Force_Mage.json:58:21: Expected json array

        "coverage": 100,
        "covers": [ "leg_l", "leg_r", "torso", "arm_l", "arm_r", "hand_l", "hand_r", "head", "foot_l", "foot_r", "mouth", "eyes" ],
        "material": "
                    ^
                     magical_material",
        "environmental_protection": 2
      }


 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1145
 VERSION  : 0ad2fdd

Same Build: 2021-10-29-0833

**Comment by TehRaccoon** [comment]
Hi, I found 4 more mods which have the "missing mandatory member "material"" error.
Here is the pastebin with all the errors: [https://pastebin.com/eN7chpha](https://pastebin.com/eN7chpha)

The mods with errors are:
- Sierra Madre (CDDA_Sierra_Madre_mod)
- PK's rebalancing (PKs_Rebalancing)
- Project Kawaii (Project_Kawaii)
- Military Proffesions Mod (More_Military)

This was tested on Linux.
I don't know the exact build of CDDA which I tested this on, but it is one from 2021-10-30 and its name is 0.F-3654-g150bb486b9.

**Comment by Nephelos** [comment]
Build : 2021-10-31-0522
 
DEBUG    : Member material_thickness of type N4cata8optionalIfEE does not support relative

 FUNCTION : bool handle_relative(const JsonObject&, const string&, MemberType&) [with MemberType = cata::optional<float>; std::enable_if_t<(! supports_relative<MemberType>::value)>* <anonymous> = 0; std::string = std::__cxx11::basic_string<char>]
 FILE     : src/generic_factory.h
 LINE     : 757
 VERSION  : 946ed1d

Managed to fix the second bug myself heres a new one its not "game breaking" unlike the next one >

 DEBUG    : Error: Json error: data/mods/Project_Kawaii/weapon.json:17:119: missing mandatory member "material"

    "volume": "2500 ml",
    "bashing": 6,
    "armor_data": { "material_thickness": 1, "armor": [ { "encumbrance": 20, "coverage": 5, "covers": [ "torso" ] } ] }
                                                                                                                      ^
                                                                                                                       ,
    "ranged_damage": { "damage_type": "stab", "amount": 8, "armor_penetration": 3 },
    "range": 5,


 FUNCTION : bool main_menu::load_character_tab(bool)
 FILE     : src/main_menu.cpp
 LINE     : 1145
 VERSION  : 946ed1d
