### ISSUE TITLE
Member material_thickness of type N4cata8optionalIfEE does not support relative

### ISSUE THREAD

**Issue by Nephelos** [Kenan2000/CDDA-Kenan-Modpack#234]
DEBUG    : Member material_thickness of type N4cata8optionalIfEE does not support relative

 FUNCTION : bool handle_relative(const JsonObject&, const string&, MemberType&) [with MemberType = cata::optional<float>; std::enable_if_t<(! supports_relative<MemberType>::value)>* <anonymous> = 0; std::string = std::__cxx11::basic_string<char>]
 FILE     : src/generic_factory.h
 LINE     : 757
 VERSION  : 18b1e6e

Build: 2021-11-03-0951

**Comment by Kenan2000** [comment]
@Nephelos Hopefully fixed thanks to @waveyl 's work
