### ISSUE TITLE
Atompot not useable in any recipies

### ISSUE THREAD

**Issue by Roet718** [Kenan2000/CDDA-Kenan-Modpack#3]
Got an Atompot in my world and it cant be used to cook anything, because no recipes allow it. Probably a problem with my mod selection.

"dda",
  "no_npc_food",
  "package_bionic_professions",
  "BL9_100monres",
  "secronom",
  "aftershock",
  "Arcana",
  "battle_maid",
  "blazeindustries",
  "crt_expansion",
  "EngineeringEssentials",
  "generatormod",
  "magiclysm",
  "magiclysm_no_class_limit",
  "Nechronica_Redux",
  "pneumo_fun",
  "mutant_npcs",
  "psychiclysm",
  "perverts",
  "XEAS",
  "rice",
  "adv_gear",
  "advtech",
  "ArmUpSurvEx",
  "arsenal_breach",
  "bioco",
  "Bionic_Space_Expander",
  "bio_recipes",
  "Bootleg_Walkers",
  "CBM_Arms",
  "SD_Magcrafting",
  "FIC_Weapons",
  "dried_fruits",
  "ExArch",
  "Uekibati_mod",
  "growable-pots",
  "Gourmand'sGraces",
  "guncotton",
  "homestead",
  "ew_pack",
  "eps_cbm",
  "magicrevamp",
  "makeshift",
  "Medieval_Mod_Reborn",
  "demon_spider_a",
  "modern_weapon",
  "MST_Extra",
  "nw_pack",
  "Pix's Shit",
  "apex",
  "futurearmory",
  "beamswordmod",
  "Soy mod",
  "cool_mod",
  "CerealMod",
  "VermilionMod",
  "thermal_ups",
  "WildLiving",
  "GOV_BANDITS",
  "crazy_labs",
  "DracoDogMod",
  "DracoPigMod",
  "modular_turrets_no_blacklist",
  "mutant_animals",
  "mutant_insects",
  "PK_REBALANCE",
  "Cata++",
  "noctpk",
  "Salvaged_Robots",
  "World_on_fire",
  "Youkai_Disco",
  "ks_variety_pack",
  "diluted_mutagens",
  "even_more_mutations",
  "food_irradiator",
  "hydroponics",
  "Mining_Mod",
  "more_survivor_notes",
  "more_survivor_stuff",
  "mutant_npcs_10492",
  "MMA",
  "MMA_Magiclysm",
  "recruitment_options",
  "tekitoumap",
  "vamp_stuff",
  "vamp_stuff+arcana",
  "more_npc",
  "Dorf_Life",
  "cityside",
  "ZSFixed_Extended_Buildings",
  "morlock_village",
  "deoxymod",
  "Tankmod_Revived",
  "necromancy",
  "amplified_players_features",
  "Graphical_Overmap",
  "Graphical_Overmap_Magiclysm",
  "Arts' Guns",
  "NM_wpns",
  "sarcophagi_access",
  "Mutation_Changes",
  "sly_beastfix",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills"
]

**Comment by Kenan2000** [comment]
@Roet718 tell me the exact name of the item "Atompot" that you're using along with the description of it - a picture would be the best in this case, oh and please, replace Blaze Industries with Blazemod - Industries is an incomplete version of Blazemod, so use Blazemod instead

**Comment by Kenan2000** [comment]
`adv_gear` has this line in requirements_override.json file ```{
    "id": "surface_heat",
    "type": "requirement",
    "//": "Heat usable for heating a surface - for example a pot or frying pan.",
    "tools": [
      [
        [ "hotplate", 1 ],
        [ "multi_cooker", 1 ],
        [ "char_smoker", 1 ],
        [ "toolset", 1 ],
        [ "fire", -1 ],
        [ "nanite_multitool_weld", -1 ]
      ]
    ]
  },
  {
    "id": "water_boiling_heat",
    "type": "requirement",
    "//": "Tools usable for providing heat usable for boiling water, but not necessarily for anything else.",
    "tools": [
      [
        [ "hotplate", 1 ],
        [ "multi_cooker", 1 ],
        [ "char_smoker", 1 ],
        [ "toolset", 1 ],
        [ "coffeemaker", 1 ],
        [ "atomic_coffeepot", -1 ],
        [ "surface_heat", 1, "LIST" ],
        [ "nanite_multitool_weld", -1 ]
      ]
    ]
  },```

Could this be the cause?

**Comment by Roet718** [comment]
Ok i changed to blaze mod. Didn't help. Atompot is a vanilla item, it cooks things like a mess kit and like other atom items it has an infinite battery life.

**Comment by Roet718** [comment]
Creating a new world without advance gear allows atompot to be used in cooking recipes again. So that does seem like the problem.

**Comment by Kenan2000** [comment]
So shall I delete the `requirements_override.json` from Advanced Gear mod then?

**Comment by Roet718** [comment]
Uhhh i guess. Not sure what that would mean since I don't know much about code, but its your mudpack man :)

**Comment by Kenan2000** [comment]
Done, removed this file - no more vanilla requirements buggy overriding :-)

**Comment by Roet718** [comment]
Nice thanks!
