### ISSUE TITLE
Segfault when loading guns

### ISSUE THREAD

**Issue by meelock** [Kenan2000/CDDA-Kenan-Modpack#4]
My game segfaults when I load any gun in a vehicle, (and vehicle guns too, it seems) with all gun mods loaded (except for generic guns) in the overrun scenario.
[crash.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/5592714/crash.log)

**Comment by Roet718** [comment]
That sounds like a vanilla issue that was supposed to be fixed in version 11183.  Try updating to that and see if it fixes.

**Comment by meelock** [comment]
Yep, that fixed it, thanks!
