### ISSUE TITLE
game is crash help

### ISSUE THREAD

**Issue by jyii5889** [Kenan2000/CDDA-Kenan-Modpack#43]
[crash.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/5946170/crash.log)
![help](https://user-images.githubusercontent.com/26016004/107269078-65c05000-6a8c-11eb-8f6d-3ed2cf3aa80d.PNG)
help me

**Comment by Kenan2000** [comment]
Cannot replicate this on latest experimental version, make sure to get the latest experimental version from here https://github.com/CleverRaven/Cataclysm-DDA/releases, and install everything according to the installation guide in the README, it explains everything thoroughly and elaborately with pictures as well

**Comment by jyii5889** [comment]
> Cannot replicate this on latest experimental version, make sure to get the latest experimental version from here https://github.com/CleverRaven/Cataclysm-DDA/releases, and install everything according to the installation guide in the README, it explains everything thoroughly and elaborately with pictures as well
