### ISSUE TITLE
another crash

### ISSUE THREAD

**Issue by jyii5889** [Kenan2000/CDDA-Kenan-Modpack#44]
[crash.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/5947107/crash.log)
help me lol

**Comment by Kenan2000** [comment]
Alright, hold on a second

**Comment by Kenan2000** [comment]
@jyii5889 There you go https://www.mediafire.com/file/jckvwa3u9xgjzch/cdda.zip/file, a pre-packaged version of latest CDDA experimental with latest versions of Mods and SDG's tileset and Soundpack, all works with no crashes and only minor and negligible small errors during world generation when you load all the mods, all you have to do is just create the world along with the save, generate it and play the game

**Comment by jyii5889** [comment]
here we go  again
![캡처](https://user-images.githubusercontent.com/26016004/107410589-d630a500-6b50-11eb-80e2-95f20d0cba87.PNG)
im done
[crash.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/5953509/crash.log)
my game dead my soul dead

**Comment by Kenan2000** [comment]
No idea how to fix this, sorry, not the Modpack's fault for sure
