### ISSUE TITLE
Broken link in README: Goats Mod Compilation

### ISSUE THREAD

**Issue by addictgamer** [Kenan2000/CDDA-Kenan-Modpack#5]
Hi, looks like this link leads to a 404 page:
```
4) https://github.com/TheGoatGod/Goats-Mod-Compilation
```

**Comment by Jarf** [comment]
Appears that it has moved to here:
https://github.com/TheGoatGod/Goats-Mod-Compilation-redux

**Comment by Kenan2000** [comment]
Thank you, addictgamer and Jarf, truly appreciate your help - fixed, thus this issue can be closed

**Comment by Theawesomeboophis** [comment]
Goat God stated that he was moving GMC to his discord, updated version is there.
