### ISSUE TITLE
3 Errors Preventing Character Creation in Latest Exp

### ISSUE THREAD

**Issue by Ichthysdekilt** [Kenan2000/CDDA-Kenan-Modpack#56]
There seem to be a number of errors on the latest exp (11537 at this time).  Screenshots attached.
![image](https://user-images.githubusercontent.com/63475824/112011351-95885c00-8afe-11eb-8ebd-fc723c5c4ba6.png)
![image](https://user-images.githubusercontent.com/63475824/112011417-a2a54b00-8afe-11eb-9b04-d031d5f959b3.png)
![image](https://user-images.githubusercontent.com/63475824/112011473-ae910d00-8afe-11eb-894c-662ba25a855f.png)

**Comment by Kenan2000** [comment]
@Ichthysdekilt There you go https://github.com/Kenan2000/CDDA-Kenan-Modpack/commit/99cc2d80bbb7dd64795ce588d4ce13dba3035023, all fixed thanks to your help :-) now, I'm not able to replicate the arcana tileset issue, tested it and it works without throwing these errors, if you find any more issues with any of the mods, always feel free to post it, I really appreciate it

**Comment by Ichthysdekilt** [comment]
@Kenan2000 I discovered that you get the Arcana error when trying to install the latest UndeadPeople tileset over the top of your mod pack.  Replacing the Arcana folder with the one in your modpack resolves the issue.  Thanks for the super quick updates!
