### ISSUE TITLE
bug on loading gun mods

### ISSUE THREAD

**Issue by Ali-Anomma** [Kenan2000/CDDA-Kenan-Modpack#57]
DEBUG    : tried to put an item (22_lr) count (0) in a container (22mag) that cannot contain it: pocket unacceptable because item is not the correct ammo type

 FUNCTION : ret_val<bool> item::put_in(const item&, item_pocket::pocket_type, bool)
 FILE     : src/item.cpp
 LINE     : 1123
#

**Comment by Kenan2000** [comment]
@Ali-Anomma I cannot replicate this error, I've spawned both High Standard Semi-Automatic pistol and High Standard HDM pistol from Modern Weapons Pack Expanded, these are the only weapons that use 22mag, I've spawned 22mag and sw22mag separately as well, successfully unloaded and reloaded both guns with each magazine and it gave me no errors, can you provide more details if any?It does not seem to be a problem with the mod's magazines or weapons

**Comment by Kenan2000** [comment]
Closing this issue because the error cannot be replicated after all the testing, so it seems that there are no errors present
