### ISSUE TITLE
On Load Issues

### ISSUE THREAD

**Issue by Ichthysdekilt** [Kenan2000/CDDA-Kenan-Modpack#58]
Some additional on-load issues.  Sorry, I feel back for reporting so much!  I hope this is helpful in some way.  This is on 11543 with your modpack, your soundpack, and the latest undeadpeople tileset.
<img width="778" alt="Screenshot 2021-03-27 172634" src="https://user-images.githubusercontent.com/63475824/112735642-0c20c180-8f24-11eb-8789-9ac0c59b7094.png">
<img width="756" alt="Screenshot 2021-03-27 172648" src="https://user-images.githubusercontent.com/63475824/112735643-0c20c180-8f24-11eb-9376-55ca320af0e3.png">
<img width="758" alt="Screenshot 2021-03-27 172658" src="https://user-images.githubusercontent.com/63475824/112735644-0c20c180-8f24-11eb-8839-e7d65129ffc4.png">
<img width="421" alt="Screenshot 2021-03-27 174148" src="https://user-images.githubusercontent.com/63475824/112735646-0cb95800-8f24-11eb-976d-fa023a64c201.png">
<img width="419" alt="Screenshot 2021-03-27 174157" src="https://user-images.githubusercontent.com/63475824/112735647-0cb95800-8f24-11eb-8198-428c42d91317.png">
<img width="869" alt="Screenshot 2021-03-27 174207" src="https://user-images.githubusercontent.com/63475824/112735649-0cb95800-8f24-11eb-961f-512cd78b437a.png">
<img width="422" alt="Screenshot 2021-03-27 174235" src="https://user-images.githubusercontent.com/63475824/112735651-0cb95800-8f24-11eb-92d6-e0afe7a24cc5.png">
<img width="689" alt="Screenshot 2021-03-27 172515" src="https://user-images.githubusercontent.com/63475824/112735652-0cb95800-8f24-11eb-9d49-aa595b4992d0.png">
<img width="666" alt="Screenshot 2021-03-27 172551" src="https://user-images.githubusercontent.com/63475824/112735653-0d51ee80-8f24-11eb-841e-cefd8769e484.png">
<img width="758" alt="Screenshot 2021-03-27 172603" src="https://user-images.githubusercontent.com/63475824/112735654-0d51ee80-8f24-11eb-8fa7-d672bb9610a8.png">
<img width="676" alt="Screenshot 2021-03-27 172613" src="https://user-images.githubusercontent.com/63475824/112735655-0d51ee80-8f24-11eb-8cc1-48d167d59d56.png">
<img width="780" alt="Screenshot 2021-03-27 172624" src="https://user-images.githubusercontent.com/63475824/112735656-0d51ee80-8f24-11eb-9d3c-554795453429.png">

**Comment by Kenan2000** [comment]
@Ichthysdekilt Uploaded the fix, thank you for your help :-) https://github.com/Kenan2000/CDDA-Kenan-Modpack/commit/eeb9b5d7a3bf350485fa92f94c7317d28ad03458
