### ISSUE TITLE
Invalid or misplaced field "override" in JSON data

### ISSUE THREAD

**Issue by mkrutov** [Kenan2000/CDDA-Kenan-Modpack#59]
[debug.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/6227377/debug.log)
cdda build cataclysmdda-0.E-Linux_x64-Tiles-b11547.tar.gz, but it has been happening for previous experimental versions as well

**Comment by Kenan2000** [comment]
@mkrutov I cannot replicate this error, have you downloaded everything correctly?You must not delete any of the mods from the cdda/data/mods directory - mainlined mods must stay untouched and installation of the Modpack is easy - you just copy the mods from the Modpack folder and then paste them to cdda/data/mods, that's the general installation guide, once again, I've done all of this on latest 11552 Windows tiles release version and cannot replicate it

**Comment by mkrutov** [comment]
Doing this steps as I'm writing this comment:

1) Download cataclysmdda-0.E-Linux_x64-Tiles-b11549.tar.gz, unpack to ~/cdda-test/cataclysmdda-0.E
2) download master.zip, unpack to ~/cdda-test/mods
3) copy over everything from ~/cdda-test/mods/Kenan-Modpack/ to ~/cdda-test/cataclysmdda-0.E/mods/
4) run the game
5) generate the world including only cataclysm++ and default mods (see attached screenshot) with default settings
![Screenshot_20210330_124129](https://user-images.githubusercontent.com/48674477/112976563-4e7d1500-9155-11eb-8f28-dec45961943a.png)

6) see second attached screenshot and debug.log
![Screenshot_20210330_124235](https://user-images.githubusercontent.com/48674477/112976664-71a7c480-9155-11eb-9972-0ccd3800e58b.png)
[debug.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/6228371/debug.log)
I'll try on a windows VM once I have a chance (later this day). However I highly doubt that this problem could be platform-specific.

**Comment by mkrutov** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/MONSTERS.md also doesn't include any "override", but I'm no expert at Cataclysm modding.

**Comment by Kenan2000** [comment]
@mkrutov It seems that there is a problem with this particular file that you've just shown, it is meant to be a compatibility file for using with other various mods such as PK rebalancing and Arcana, if they are not enabled in your world, it might as well throw errors, I believe, I will get in contact with one of it's authors and revert to you when possible

**Comment by mkrutov** [comment]
Knowing that, pushing bit further still generates me (different) error. 

I've created a new world enabling Arcana, PK and Cata++ (in that specific order, if Cata++ precedes PK and Arcana obviously error stays the same.) 
Creating a character in that world generates (different) error, see screenshot. 
![Screenshot_20210330_124235](https://user-images.githubusercontent.com/48674477/112978799-0d3a3480-9158-11eb-8bc0-c3c594f196f1.png)

Removing PK's rebalance eliminates that error.

More dependency issues?

**Comment by Kenan2000** [comment]
Closing this for now, since this issue in Cata++ has been fixed as well, feel free to post another issue whenever you encounter one as well
