### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by bubbaray9000** [Kenan2000/CDDA-Kenan-Modpack#62]
Can you help me with this?
[crash.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/6261671/crash.log)

**Comment by Kenan2000** [comment]
@bubbaray9000 The crash.log file provides no information of whatsoever to resolve this issue that you've come across, if you can't replicate a crash with a certain mod on or trace the mod that causes the crash, it's definitely a problem with one of the latest experimental versions, not the mods or the Modpack's fault at all
