### ISSUE TITLE
Creature List Starting Traits Error

### ISSUE THREAD

**Issue by Ichthysdekilt** [Kenan2000/CDDA-Kenan-Modpack#63]
Heya!  I'm getting this every few in game days-ish.
<img width="692" alt="Screenshot 2021-04-06 213526" src="https://user-images.githubusercontent.com/63475824/113797953-35a9cc00-9720-11eb-9725-ba35fae126da.png">

[mods.json.txt](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/6268420/mods.json.txt)

Please let me know if there's anything else I can provide or anything I can help with!  I appreciate all that you're doing!  Do you happen to have a patreon?

**Comment by Theawesomeboophis** [comment]
Starting_trait_n_rolls has been removed in the recent update, is this problem fixed or does it still persist with latest version?

**Comment by Ichthysdekilt** [comment]
I haven't seen it since the last update - thank you!
