### ISSUE TITLE
Advanced Gear-CDDA-Mod Nano recipe seems unlock without requirement?

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/CDDA-Kenan-Modpack#66]
I can see lots of things in &'s Nano tab, in level 1 skill, where can I issue to suggest change this?

**Comment by linonetwo** [comment]
https://github.com/Lorith/AdvancedGear-CDDA-Mod seems not updated for a long time?

**Comment by Kenan2000** [comment]
@linonetwo This is Shard on our CDDA Modding Community server, he is currently working on updating AdvancedGear Mod, you can ping him on our server and provide him any suggestions that you have :-)
