### ISSUE TITLE
Strange Segmentation Fault when driving.

### ISSUE THREAD

**Issue by meelock** [Kenan2000/CDDA-Kenan-Modpack#7]
I was driving my tank near a castle of hell and my game segmentation faulted saying that it played an invalid sound.

Crash log:
[crash.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/5611224/crash.log)
Debug:
[debug.log](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/5611225/debug.log)
Save File:
[Toco.zip](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/5611227/Toco.zip)

**Comment by Kenan2000** [comment]
@meelock did it crash **INSTANTLY** after the invalid sound or some time after that?I've been getting `tried to play a bad sound frame error` sometimes checking in my debug.log but it never caused a crash, possibly there COULD be a broken music file or something similar to it in the Otopack soundpack of mine, but it should not be causing such serious segmentation fault errors, this could be related to the vanilla game itself or one of the mods, but not the soundpack, I believe...

**Comment by meelock** [comment]
Can't replicate, closing issue.
