### ISSUE TITLE
The guns in Artyom_Emporium should have belt mod location

### ISSUE THREAD

**Issue by MikuMiddo** [Kenan2000/CDDA-Kenan-Modpack#70]
The gun belt now has its own mod location for guns.So now all the guns in Artyom_Emporium cannot attach the gun belt on it.
This make carry gun so difficult,please add the mod location for all of these guns

**Comment by Kenan2000** [comment]
> The gun belt now has its own mod location for guns

Can you please elaborate?Can you link the commit with the changes in vanilla that you're mentioning here?

**Comment by MikuMiddo** [comment]
> > The gun belt now has its own mod location for guns
> 
> Can you please elaborate?Can you link the commit with the changes in vanilla that you're mentioning here?

![image](https://user-images.githubusercontent.com/53809752/114715322-8a26fa00-9d65-11eb-826d-b8678de6e820.png)
Here you can see a valid_mod_locations called **sling**.this is where the gun belt mod use.
But in Artyom_Emporium mod,all gun including rifle don't have one
![image](https://user-images.githubusercontent.com/53809752/114716069-47b1ed00-9d66-11eb-8e4e-c8eb730f7a19.png)

I am sorry but I have found for a while, but can't find the commits :P,maybe it hide in a big commit.

**Comment by MikuMiddo** [comment]
> > The gun belt now has its own mod location for guns
> 
> Can you please elaborate?Can you link the commit with the changes in vanilla that you're mentioning here?

The gun belt used to be use the accessories valid_mod_locations,but now it has its own.
Maybe you can add one **sling** valid_mod_locations to the guns that you think it can have one on it.

**Comment by Kenan2000** [comment]
> > > The gun belt now has its own mod location for guns
> > 
> > 
> > Can you please elaborate?Can you link the commit with the changes in vanilla that you're mentioning here?
> 
> The gun belt used to be use the accessories valid_mod_locations,but now it has its own.
> Maybe you can add one **sling** valid_mod_locations to the guns that you think it can have one on it.

Will do this once I get some time, I'll add slings to all rifles and shotguns as well in Artyom_Emporium, working on this right now

**Comment by MikuMiddo** [comment]
> > > > The gun belt now has its own mod location for guns
> > > 
> > > 
> > > Can you please elaborate?Can you link the commit with the changes in vanilla that you're mentioning here?
> > 
> > 
> > The gun belt used to be use the accessories valid_mod_locations,but now it has its own.
> > Maybe you can add one **sling** valid_mod_locations to the guns that you think it can have one on it.
> 
> Will do this once I get some time, I'll add slings to all rifles and shotguns as well in Artyom_Emporium, working on this right now

OK，Thankyou

**Comment by Kenan2000** [comment]
> > > The gun belt now has its own mod location for guns
> > 
> > 
> > Can you please elaborate?Can you link the commit with the changes in vanilla that you're mentioning here?
> 
> The gun belt used to be use the accessories valid_mod_locations,but now it has its own.
> Maybe you can add one **sling** valid_mod_locations to the guns that you think it can have one on it.

@MikuMiddo I've updated majority of gun mods in both Modpacks adding sling additions to most of the two handed weapons that are rifles, shotguns, smgs, launchers, energy weapons as well, here https://github.com/Kenan2000/CDDA-Kenan-Modpack/commit/cfb7b8ca40216c5f4d539c0189f77e95c66fe830

**Comment by MikuMiddo** [comment]
> > > > The gun belt now has its own mod location for guns
> > > 
> > > 
> > > Can you please elaborate?Can you link the commit with the changes in vanilla that you're mentioning here?
> > 
> > 
> > The gun belt used to be use the accessories valid_mod_locations,but now it has its own.
> > Maybe you can add one **sling** valid_mod_locations to the guns that you think it can have one on it.
> 
> @MikuMiddo I've updated majority of gun mods in both Modpacks adding sling additions to most of the two handed weapons that are rifles, shotguns, smgs, launchers, energy weapons as well, here [cfb7b8c](https://github.com/Kenan2000/CDDA-Kenan-Modpack/commit/cfb7b8ca40216c5f4d539c0189f77e95c66fe830) , feel free to suggest more additions if you come across something that the mods lack that vanilla has or some problems or unbalanced things that need to be tweaked basically

Wow that's a lot of work,Thank you for your hardworking.I will throw the issue ASAP I meet them =D;
