### ISSUE TITLE
A Number of Small Issues

### ISSUE THREAD

**Issue by Ichthysdekilt** [Kenan2000/CDDA-Kenan-Modpack#71]
<img width="470" alt="22_lr coltsmg" src="https://user-images.githubusercontent.com/63475824/114799153-fce3a580-9d64-11eb-9305-0e06447ba74a.png">
<img width="478" alt="22_lr hk_mp5eod" src="https://user-images.githubusercontent.com/63475824/114799155-fce3a580-9d64-11eb-86fb-ef498d5d6996.png">
<img width="451" alt="22_lr M1_9" src="https://user-images.githubusercontent.com/63475824/114799157-fce3a580-9d64-11eb-96e8-5b6dcb77572a.png">
<img width="763" alt="Bad Spawn" src="https://user-images.githubusercontent.com/63475824/114799158-fd7c3c00-9d64-11eb-8311-628a70ef7480.png">
<img width="424" alt="Error Making Ubuntu Laptop 2" src="https://user-images.githubusercontent.com/63475824/114799159-fd7c3c00-9d64-11eb-9739-8a1071cb6bfe.png">
<img width="524" alt="Error Making Ubuntu Laptop 3" src="https://user-images.githubusercontent.com/63475824/114799160-fd7c3c00-9d64-11eb-84fe-fe259434e81f.png">
<img width="417" alt="Error Making Ubuntu Laptop 4" src="https://user-images.githubusercontent.com/63475824/114799161-fd7c3c00-9d64-11eb-9a17-480a5ec8f44f.png">
<img width="428" alt="Error Making Ubuntu Laptop" src="https://user-images.githubusercontent.com/63475824/114799163-fd7c3c00-9d64-11eb-8b8c-232598ab3ab2.png">
<img width="791" alt="Hobo Stove Ammo 2" src="https://user-images.githubusercontent.com/63475824/114799164-fe14d280-9d64-11eb-9b5e-529eaab08add.png">
<img width="800" alt="Hobo Stove Ammo" src="https://user-images.githubusercontent.com/63475824/114799165-fe14d280-9d64-11eb-9f32-5fcf2ae3b938.png">
<img width="800" alt="Negative Cal Tofu" src="https://user-images.githubusercontent.com/63475824/114799305-56e46b00-9d65-11eb-831f-d97afd2410a7.png">

[mods.txt](https://github.com/Kenan2000/CDDA-Kenan-Modpack/files/6314559/mods.txt)

Please let me know if any of these are not the mods and I'll be happy to report them in their appropriate places instead!

**Comment by Kenan2000** [comment]
@Ichthysdekilt I've fixed majority of these errors in one of the latest updates https://github.com/Kenan2000/CDDA-Kenan-Modpack/commit/cfb7b8ca40216c5f4d539c0189f77e95c66fe830, if you come across any other problems, feel free to post an issue whenever you want and I'll look into it when I can

**Comment by Ichthysdekilt** [comment]
Thank you thank you @Kenan2000 !  You're the bomb!
