### ISSUE TITLE
Misplaced Indicators on UndeadPeople tileset

### ISSUE THREAD

**Issue by heretic01** [Kenan2000/CDDA-Kenan-Modpack#76]
![Снимок экрана (1)](https://user-images.githubusercontent.com/54194189/116185181-c5dc9f00-a729-11eb-91e7-a600a5259b05.png)
![Снимок экрана (2)](https://user-images.githubusercontent.com/54194189/116185185-c70dcc00-a729-11eb-9b7e-7f5cd3d9eba8.png)
![Снимок экрана (3)](https://user-images.githubusercontent.com/54194189/116185187-c7a66280-a729-11eb-8a44-688ead8eb4fe.png)
![Снимок экрана (4)](https://user-images.githubusercontent.com/54194189/116185188-c83ef900-a729-11eb-9c54-3849fd451e8c.png)

**Comment by heretic01** [comment]
It would be great to know what causes the bug, or at least to know in which mod files I should look for changes in indicators.

**Comment by Kenan2000** [comment]
@heretic01 The maintainer of these graphics related mods is SDG, the great and awesome gigantic tileset creator, he says that on latest experimental versions all the mods that add indicators as well as the ones that start with MSX and add indicators are broken and these graphical errors can't be fixed basically, not sure how it is in 0_E3 and Bright Nights, it may work there, according to his words, you should just disable MSX indicator mods, all of them, oh and don't play with the desert mod, it's a broken mess that basically ruins the entire world generation of the game and mods as well, can we close the issue now or you have any other questions?

**Comment by heretic01** [comment]
@Kenan2000 Oh, a huge thanks and спасибо for your reply. I have disabled mentioned mods and the problem became solved. Yes, I’ll close the issue in a minute. And while I have the opportunity, I’d love to complement the work you're doing with all these mods. Thank you and have a great day :)
