### ISSUE TITLE
Add Whaley's Weird World

### ISSUE THREAD

**Issue by Theawesomeboophis** [Kenan2000/CDDA-Kenan-Modpack#79]
This is a mod I am interested in playing with, but I can't find a working link anywhere and I thought it would be beneficial to have it in the modpack.

**Comment by Kenan2000** [comment]
@Theawesomeboophis I can't find this mod anywhere as well as you so I'll have to close this for now, if you manage to find it's files or link to it, kindly provide it here if you can :-)

**Comment by Theawesomeboophis** [comment]
The only link I can find is on nofile.io which is a website that no longer exist, Is Whaley still active? If so, someone could probably ask him on Reddit ( I would do it myself, but I don't have a Reddit account).

**Comment by Theawesomeboophis** [comment]
Alternatively, I could try recreating the mod based on what is known about it, such as monster IDs and the Reddit post have some info about the contents of the mod.

**Comment by Theawesomeboophis** [comment]
I have begun my recreation attempt at https://github.com/Theawesomeboophis/Whaleys-Weird-World-Recreation, obviously will probably not be the same as original mod, but I will try my best.

**Comment by Theawesomeboophis** [comment]
Not sure how to make CIA agent actually use their gun, will try to make it function though.

**Comment by Theawesomeboophis** [comment]
I have added tileset support previously implemented in UndeadPeopleLegacy.
