### ISSUE TITLE
Reapermod causes Segmentation Fault when switching to Shinigami Song

### ISSUE THREAD

**Issue by Chailles** [Kenan2000/CDDA-Kenan-Modpack#8]
As the title says, if you learn the style and you attempt to switch to it, the game crashes.

It seems like this is due to the `"initiate": [  ],` being blank in the mod's martialarts.json. Apparently it's required that at least some text be in there.

**Comment by Kenan2000** [comment]
@Chailles just uploaded a fix, check it out and, please, let me know if it works now, and thank you for posting about this error, I truly appreciate it :-)

**Comment by Chailles** [comment]
Yep, the game no longer crashes when selecting the stance. Closing issue.
