### ISSUE TITLE
Is shot_410 disappeared?

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/CDDA-Kenan-Modpack#80]
https://github.com/Kenan2000/CDDA-Kenan-Modpack/blob/f46d870014d81158734f3eb96e7e2646a04ba615/Kenan-Modpack/PKs_Rebalancing/mod_tileset.json#L82

I get 

```python
18:12:58.410 ERROR : src/item_factory.cpp:1553 [const itype *Item_factory::find_template(const itype_id &) const] Missing item definition: shot_410
18:13:12.003 ERROR : src/savegame_json.cpp:2578 [void item::io(Archive &) [Archive = io::JsonObjectInputArchive]] Item shot_410 was loaded with charges, but can not have any!
```

**Comment by Kenan2000** [comment]
@linonetwo Well, thanks to CV514's work I've replaced shot_410 with 410shot_000, altered the recipe a bit as well, it does not throw any errors here on latest version, once you get the latest version, it should stop throwing this error pretty much
