### ISSUE TITLE
"Mapgen house is not used by anything!" and "unknown content cityside" and "Missing item definition: shot_410"

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/CDDA-Kenan-Modpack#84]
After merging latest update https://github.com/linonetwo/CDDA-Kenan-Modpack-Chinese/commit/3ee1ac22ba56c8975fbfb6e49926abad1fcbd7e1

I got errors upon loading existing save:

```
Backtrace emission took 0 seconds.
(continued from above) ERROR : src/game.cpp:3086 [bool game::load_packs(const std::string &, const std::vector<mod_id> &, loading_ui &)] unknown content cityside
02:16:25.334 ERROR : src/game.cpp:3086 [bool game::load_packs(const std::string &, const std::vector<mod_id> &, loading_ui &)] unknown content ZSFixed_Extended_Buildings
02:16:26.295 WARNING : opendir [/Users/linonetwo/Library/Application Support/Cataclysm/save/新道路/mods] failed with "No such file or directory".
02:16:38.333 ERROR SDL : src/cata_tiles.cpp:629: Mod tileset in "data/mods//sees_player_retro/mod_tileset.json" is not compatible.
02:16:38.333 ERROR SDL : src/cata_tiles.cpp:629: Mod tileset in "/Users/linonetwo/Library/Application Support/Cataclysm/mods//Kenan-Modpack-Chinese/amplified_player_features/mod_tileset.json" is not compatible.
02:16:38.541 INFO : Loaded tileset: Chibi_Ultica
02:16:44.881 ERROR : src/mapgen.cpp:329 [void mapgen_factory::check_consistency()] Mapgen house is not used by anything!
02:16:55.722 ERROR : src/item_factory.cpp:1553 [const itype *Item_factory::find_template(const itype_id &) const] Missing item definition: shot_410
```

**Comment by Kenan2000** [comment]
@linonetwo Hmm, remove cityside and ZSFixed_Extended_Buildings from your cdda/save/mods.json file, try generating a new world and see if you still get these errors on latest version, these updates are not technically compatible with older saves, if these old variants of the ammo have already generated as well

**Comment by linonetwo** [comment]
Ok, I will remove the mod and try to clean the save file manually.

BTW, are those buildings move into other mods? I think one of the joys of playing CDDA is exploring those buildings.

**Comment by linonetwo** [comment]
This error presists when create a new save:

```log
 DEBUG    : Mapgen house is not used by anything!

 FUNCTION : void mapgen_factory::check_consistency()
 FILE     : src/mapgen.cpp
 LINE     : 329
```

**Comment by Kenan2000** [comment]
> Ok, I will remove the mod and try to clean the save file manually tonight after work.
> 
> BTW, are those buildings move into other mods? I think one of the joys of playing CDDA is exploring those buildings.

Mods that I've deleted have buildings which were merged in vanilla some time ago, which is why I've removed them since they already exist in vanilla



> This error presists when create a new save:
> 
> ```
>  DEBUG    : Mapgen house is not used by anything!
> 
>  FUNCTION : void mapgen_factory::check_consistency()
>  FILE     : src/mapgen.cpp
>  LINE     : 329
> ```

Hmm, would you be able to help me to trace mod that causes this error if that's okay?

**Comment by linonetwo** [comment]
After 2-partitation test, I think it is in `"Ninja"` mod.

**Comment by linonetwo** [comment]
I think it is here

https://github.com/Kenan2000/CDDA-Kenan-Modpack/blob/ab2ce4bb3add3abe1950266903962b9dec8a44c3/Kenan-Modpack/Ninja_mod/map/ninja_mapgen_yakuza_office.json#L5

What does this:

```json
    "om_terrain": [
      "house"
    ],
```

means?

And how to let this om "used"?

**Comment by Kenan2000** [comment]
Hopefully this fixes it https://github.com/Kenan2000/CDDA-Kenan-Modpack/commit/93f2f0b50babac180129aa67f0c442e037ee3fa6, take a look at it

**Comment by linonetwo** [comment]
Okay, so the error message should have been "mapgen house is not defined by anything"

The current one misleads me to think there is an unused house definition.

**Comment by linonetwo** [comment]
I tried this, but `"mapgen house is not defined by anything"` still exists...

**Comment by linonetwo** [comment]
I think it might be `tekitoumap`, it has mapgen house.

**Comment by linonetwo** [comment]
On seems you fixes it in the latest update. Thank you.
