### ISSUE TITLE
cdda++ acs 74 stealth cloak after load the game cannot invisibility

### ISSUE THREAD

**Issue by HeYaoDaDa** [Kenan2000/CDDA-Kenan-Modpack#85]
It could be not have "     ,"ench_effects":[{"effect":"invisibility","intensity":1}]    " in passive_effects .
![O)Q0RHY%9 G{UT%610GGI00](https://user-images.githubusercontent.com/37257891/119348670-c4be7380-bccf-11eb-9e35-4785827367d6.png),I add after can intensity

**Comment by Kenan2000** [comment]
@HeYaoDaDa Suggesting you to make an issue on official mod's repository page https://github.com/Noctifer-de-Mortem/nocts_cata_mod, no idea how to fix this for now pretty much

**Comment by HeYaoDaDa** [comment]
> @HeYaoDaDa Suggesting you to make an issue on official mod's repository page https://github.com/Noctifer-de-Mortem/nocts_cata_mod, no idea how to fix this for now pretty much

ok
