### ISSUE TITLE
Battle Maid: Human carry bag doesn't work

### ISSUE THREAD

**Issue by bicobus** [Kenan2000/CDDA-Kenan-Modpack#97]
Starting as "Maid with master", provides you with a carry bag and your master. Once released, the master can't go back in the bag.
```
ERROR : src/iuse.cpp:9337 [cata::optional<int> iuse::capture_monster_act(player*, item*, bool, const tripoint&)] <color_c_light_green>|| </color>human-sized carry bag has no creature_size_capacity.
```

**Comment by Theawesomeboophis** [comment]
Can you test the fix I submitted and make sure it works? I would appreciate it.

**Comment by Theawesomeboophis** [comment]
Can you test the fix I submitted and see if the error is gone? Thanks.

**Comment by bicobus** [comment]
Yep, that fixes it.
